/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: amogusstrikesback2 (https://sketchfab.com/amogusstrikesback2)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stumble-guys-stumble-soccer-2bb2622cf64e4a969fdcb656eaafa4ff
Title: stumble guys stumble soccer
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/pitch.glb")
  return (
    <group {...props} dispose={null} scale={10}>
      <group scale={0.01}>
        <group position={[0, 4.1, -64.8]} rotation={[0.576, 0, 0]}>
          <group position={[-0.051, -0.058, 0]}>
            <group
              position={[-0.12, -0.079, 0.155]}
              rotation={[-0.097, 0, 0]}
              scale={0.91}
            >
              <group position={[0.045, -0.052, 0]}>
                <mesh
                  geometry={nodes.Wea001_Gun03_Mat001_Gun01_0.geometry}
                  material={materials.Mat001_Gun01}
                  position={[-0.045, 0.052, 0]}
                />
              </group>
            </group>
            <group
              position={[-0.14, -0.112, 0.147]}
              rotation={[-0.16, 0.112, 0.048]}
            >
              <group position={[0.045, -0.052, 0]}>
                <mesh
                  geometry={nodes.Wea001_Gun03001_Mat001_Gun02_0.geometry}
                  material={materials.Mat001_Gun02}
                  position={[-0.045, 0.051, 0]}
                />
              </group>
            </group>
            <group
              position={[-0.122, -0.094, 0.14]}
              rotation={[-0.131, 0, 0]}
              scale={[0.93, 0.93, 0.9]}
            >
              <group position={[0.045, -0.052, 0]}>
                <mesh
                  geometry={nodes.Wea001_Gun03003_Mat001_Gun03_0.geometry}
                  material={materials.Mat001_Gun03}
                  position={[-0.045, 0.052, 0]}
                />
              </group>
            </group>
          </group>
        </group>
        <group position={[0, 4.1, -64.8]} rotation={[0.576, 0, 0]}>
          <group position={[-0.051, -0.058, 0]}>
            <group
              position={[-0.12, -0.079, 0.155]}
              rotation={[-0.097, 0, 0]}
              scale={0.91}
            >
              <group position={[0.045, -0.052, 0]}>
                <mesh
                  geometry={nodes.Wea001_Gun03004_Mat001_Gun01_0.geometry}
                  material={materials.Mat001_Gun01}
                  position={[-0.045, 0.052, 0]}
                />
              </group>
            </group>
            <group
              position={[-0.14, -0.112, 0.147]}
              rotation={[-0.16, 0.112, 0.048]}
            >
              <group position={[0.045, -0.052, 0]}>
                <mesh
                  geometry={nodes.Wea001_Gun03005_Mat001_Gun02_0.geometry}
                  material={materials.Mat001_Gun02}
                  position={[-0.045, 0.051, 0]}
                />
              </group>
            </group>
            <group
              position={[-0.122, -0.094, 0.14]}
              rotation={[-0.131, 0, 0]}
              scale={[0.93, 0.93, 0.9]}
            >
              <group position={[0.045, -0.052, 0]}>
                <mesh
                  geometry={nodes.Wea001_Gun03007_Mat001_Gun03_0.geometry}
                  material={materials.Mat001_Gun03}
                  position={[-0.045, 0.052, 0]}
                />
              </group>
            </group>
          </group>
        </group>
        <group position={[0, 4.1, -64.8]} rotation={[0.576, 0, 0]}>
          <group position={[-0.051, -0.058, 0]}>
            <group
              position={[-0.12, -0.079, 0.155]}
              rotation={[-0.097, 0, 0]}
              scale={0.91}
            >
              <group position={[0.045, -0.052, 0]}>
                <mesh
                  geometry={nodes.Wea001_Gun03008_Mat001_Gun01_0.geometry}
                  material={materials.Mat001_Gun01}
                  position={[-0.045, 0.052, 0]}
                />
              </group>
            </group>
            <group
              position={[-0.14, -0.112, 0.147]}
              rotation={[-0.16, 0.112, 0.048]}
            >
              <group position={[0.045, -0.052, 0]}>
                <mesh
                  geometry={nodes.Wea001_Gun03009_Mat001_Gun02_0.geometry}
                  material={materials.Mat001_Gun02}
                  position={[-0.045, 0.051, 0]}
                />
              </group>
            </group>
            <group
              position={[-0.122, -0.094, 0.14]}
              rotation={[-0.131, 0, 0]}
              scale={[0.93, 0.93, 0.9]}
            >
              <group position={[0.045, -0.052, 0]}>
                <mesh
                  geometry={nodes.Wea001_Gun03011_Mat001_Gun03_0.geometry}
                  material={materials.Mat001_Gun03}
                  position={[-0.045, 0.052, 0]}
                />
              </group>
            </group>
          </group>
        </group>
        <group position={[0, -4.79, 0]}>
          <mesh
            geometry={nodes.Level10VisualsExtra_stands_wall_0.geometry}
            material={materials.stands_wall}
          />
          <mesh
            geometry={nodes.Level10VisualsExtra_stands_seating3_0.geometry}
            material={materials.stands_seating3}
          />
        </group>
        <group position={[0, -4.79, 0]}>
          <mesh>
            <boxGeometry args={[1, 1, 1]} />
          </mesh>
          <mesh
            geometry={nodes.Level10Visuals_soccerfield_0.geometry}
            material={materials.soccerfield}
          />
          <mesh
            geometry={nodes.Level10Visuals_lines_0.geometry}
            material={materials.lines}
          />
          <mesh
            geometry={nodes.Level10Visuals_orange_0.geometry}
            material={materials.orange}
          />
          <mesh
            geometry={nodes.Level10Visuals_goalpadding_orange_0.geometry}
            material={materials.goalpadding_orange}
          />
          <mesh
            geometry={nodes.Level10Visuals_goal_orange_0.geometry}
            material={materials.goal_orange}
          />
          <mesh
            geometry={nodes.Level10Visuals_blue_0.geometry}
            material={materials.blue}
          />
          <mesh
            geometry={nodes.Level10Visuals_goalpadding_blue_0.geometry}
            material={materials.goalpadding_blue}
          />
          <mesh
            geometry={nodes.Level10Visuals_goal_blue_0.geometry}
            material={materials.goal_blue}
          />
        </group>
        <group position={[0, -1.55, 0]}>
          <group position={[-15.13, 5.05, 12.649]}>
            <mesh
              geometry={nodes.FencePostYellow_Fence_0.geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={nodes.collision_cylinder8_no_bottom_No_Name_0.geometry}
              material={materials.No_Name}
              position={[0, 0.155, 0]}
              scale={[0.198, 0.492, 0.198]}
            />
          </group>
          <group position={[-15.13, 5.43, 12.492]} scale={[1, 1, 0.549]}>
            <mesh
              geometry={nodes.FenceLongYellow_Fence_0.geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={nodes["collision_box_Default-Material_0"].geometry}
              material={materials["Default-Material"]}
              position={[0, -0.102, -5.543]}
              scale={[0.13, 0.22, 5.724]}
            />
          </group>
          <group position={[-15.13, 5.05, 6.312]}>
            <mesh
              geometry={nodes["FencePostYellow_(1)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={
                nodes.collision_cylinder8_no_bottom001_No_Name_0.geometry
              }
              material={materials.No_Name}
              position={[0, 0.155, 0]}
              scale={[0.198, 0.492, 0.198]}
            />
          </group>
          <group position={[-15.13, 5.43, 6.154]} scale={[1, 1, 0.549]}>
            <mesh
              geometry={nodes["FenceLongYellow_(1)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={nodes["collision_box001_Default-Material_0"].geometry}
              material={materials["Default-Material"]}
              position={[0, -0.102, -5.543]}
              scale={[0.13, 0.22, 5.724]}
            />
          </group>
          <group position={[-15.13, 5.05, -0.049]}>
            <mesh
              geometry={nodes["FencePostYellow_(2)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={
                nodes.collision_cylinder8_no_bottom002_No_Name_0.geometry
              }
              material={materials.No_Name}
              position={[0, 0.155, 0]}
              scale={[0.198, 0.492, 0.198]}
            />
          </group>
          <group position={[-15.13, 5.43, -0.206]} scale={[1, 1, 0.549]}>
            <mesh
              geometry={nodes["FenceLongYellow_(2)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={nodes["collision_box002_Default-Material_0"].geometry}
              material={materials["Default-Material"]}
              position={[0, -0.102, -5.543]}
              scale={[0.13, 0.22, 5.724]}
            />
          </group>
          <group position={[-15.13, 5.05, -6.42]}>
            <mesh
              geometry={nodes["FencePostYellow_(3)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={
                nodes.collision_cylinder8_no_bottom003_No_Name_0.geometry
              }
              material={materials.No_Name}
              position={[0, 0.155, 0]}
              scale={[0.198, 0.492, 0.198]}
            />
          </group>
          <group position={[-15.13, 5.43, -6.578]} scale={[1, 1, 0.549]}>
            <mesh
              geometry={nodes["FenceLongYellow_(3)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={nodes["collision_box003_Default-Material_0"].geometry}
              material={materials["Default-Material"]}
              position={[0, -0.102, -5.543]}
              scale={[0.13, 0.22, 5.724]}
            />
          </group>
          <group position={[-15.13, 5.05, -12.769]}>
            <mesh
              geometry={nodes["FencePostYellow_(4)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={
                nodes.collision_cylinder8_no_bottom004_No_Name_0.geometry
              }
              material={materials.No_Name}
              position={[0, 0.155, 0]}
              scale={[0.198, 0.492, 0.198]}
            />
          </group>
          <group
            position={[-7.324, 5.43, -20.18]}
            rotation={[0, -1.571, 0]}
            scale={[1, 1, 0.446]}
          >
            <mesh
              geometry={nodes["FenceLongYellow_(8)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={nodes["collision_box004_Default-Material_0"].geometry}
              material={materials["Default-Material"]}
              position={[0, -0.102, -5.543]}
              scale={[0.13, 0.22, 5.724]}
            />
          </group>
          <group position={[-7.46, 5.05, -20.18]} rotation={[0, -1.571, 0]}>
            <mesh
              geometry={nodes["FencePostYellow_(11)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={
                nodes.collision_cylinder8_no_bottom005_No_Name_0.geometry
              }
              material={materials.No_Name}
              position={[0, 0.155, 0]}
              scale={[0.198, 0.492, 0.198]}
            />
          </group>
          <group position={[-2.27, 5.05, -20.18]} rotation={[0, -1.571, 0]}>
            <mesh
              geometry={nodes["FencePostYellow_(12)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={
                nodes.collision_cylinder8_no_bottom006_No_Name_0.geometry
              }
              material={materials.No_Name}
              position={[0, 0.155, 0]}
              scale={[0.198, 0.492, 0.198]}
            />
          </group>
          <group
            position={[-2.158, 5.43, -20.18]}
            rotation={[0, -1.571, 0]}
            scale={[1, 1, 0.446]}
          >
            <mesh
              geometry={nodes["FenceLongYellow_(10)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={nodes["collision_box005_Default-Material_0"].geometry}
              material={materials["Default-Material"]}
              position={[0, -0.102, -5.543]}
              scale={[0.13, 0.22, 5.724]}
            />
          </group>
          <group position={[2.89, 5.05, -20.18]} rotation={[0, -1.571, 0]}>
            <mesh
              geometry={nodes["FencePostYellow_(13)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={
                nodes.collision_cylinder8_no_bottom007_No_Name_0.geometry
              }
              material={materials.No_Name}
              position={[0, 0.155, 0]}
              scale={[0.198, 0.492, 0.198]}
            />
          </group>
          <group
            position={[3.017, 5.43, -20.18]}
            rotation={[0, -1.571, 0]}
            scale={[1, 1, 0.446]}
          >
            <mesh
              geometry={nodes["FenceLongYellow_(11)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={nodes["collision_box006_Default-Material_0"].geometry}
              material={materials["Default-Material"]}
              position={[0, -0.102, -5.543]}
              scale={[0.13, 0.22, 5.724]}
            />
          </group>
          <group position={[8.09, 5.05, -20.18]} rotation={[0, -1.571, 0]}>
            <mesh
              geometry={nodes["FencePostYellow_(14)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={
                nodes.collision_cylinder8_no_bottom008_No_Name_0.geometry
              }
              material={materials.No_Name}
              position={[0, 0.155, 0]}
              scale={[0.198, 0.492, 0.198]}
            />
          </group>
          <group
            position={[-7.324, 5.43, 20.18]}
            rotation={[0, -1.571, 0]}
            scale={[1, 1, 0.446]}
          >
            <mesh
              geometry={nodes["FenceLongYellow_(9)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={nodes["collision_box007_Default-Material_0"].geometry}
              material={materials["Default-Material"]}
              position={[0, -0.102, -5.543]}
              scale={[0.13, 0.22, 5.724]}
            />
          </group>
          <group position={[-7.46, 5.05, 20.18]} rotation={[0, -1.571, 0]}>
            <mesh
              geometry={nodes["FencePostYellow_(15)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={
                nodes.collision_cylinder8_no_bottom009_No_Name_0.geometry
              }
              material={materials.No_Name}
              position={[0, 0.155, 0]}
              scale={[0.198, 0.492, 0.198]}
            />
          </group>
          <group position={[-2.27, 5.05, 20.18]} rotation={[0, -1.571, 0]}>
            <mesh
              geometry={nodes["FencePostYellow_(16)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={
                nodes.collision_cylinder8_no_bottom010_No_Name_0.geometry
              }
              material={materials.No_Name}
              position={[0, 0.155, 0]}
              scale={[0.198, 0.492, 0.198]}
            />
          </group>
          <group
            position={[-2.158, 5.43, 20.18]}
            rotation={[0, -1.571, 0]}
            scale={[1, 1, 0.446]}
          >
            <mesh
              geometry={nodes["FenceLongYellow_(12)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={nodes["collision_box008_Default-Material_0"].geometry}
              material={materials["Default-Material"]}
              position={[0, -0.102, -5.543]}
              scale={[0.13, 0.22, 5.724]}
            />
          </group>
          <group position={[2.89, 5.05, 20.18]} rotation={[0, -1.571, 0]}>
            <mesh
              geometry={nodes["FencePostYellow_(17)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={
                nodes.collision_cylinder8_no_bottom011_No_Name_0.geometry
              }
              material={materials.No_Name}
              position={[0, 0.155, 0]}
              scale={[0.198, 0.492, 0.198]}
            />
          </group>
          <group
            position={[3.017, 5.43, 20.18]}
            rotation={[0, -1.571, 0]}
            scale={[1, 1, 0.446]}
          >
            <mesh
              geometry={nodes["FenceLongYellow_(13)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={nodes["collision_box009_Default-Material_0"].geometry}
              material={materials["Default-Material"]}
              position={[0, -0.102, -5.543]}
              scale={[0.13, 0.22, 5.724]}
            />
          </group>
          <group position={[8.09, 5.05, 20.18]} rotation={[0, -1.571, 0]}>
            <mesh
              geometry={nodes["FencePostYellow_(18)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={
                nodes.collision_cylinder8_no_bottom012_No_Name_0.geometry
              }
              material={materials.No_Name}
              position={[0, 0.155, 0]}
              scale={[0.198, 0.492, 0.198]}
            />
          </group>
          <group position={[15.08, 5.05, 12.649]}>
            <mesh
              geometry={nodes["FencePostYellow_(5)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={
                nodes.collision_cylinder8_no_bottom013_No_Name_0.geometry
              }
              material={materials.No_Name}
              position={[0, 0.155, 0]}
              scale={[0.198, 0.492, 0.198]}
            />
          </group>
          <group position={[15.08, 5.43, 12.492]} scale={[1, 1, 0.549]}>
            <mesh
              geometry={nodes["FenceLongYellow_(4)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={nodes["collision_box010_Default-Material_0"].geometry}
              material={materials["Default-Material"]}
              position={[0, -0.102, -5.543]}
              scale={[0.13, 0.22, 5.724]}
            />
          </group>
          <group position={[15.08, 5.05, 6.312]}>
            <mesh
              geometry={nodes["FencePostYellow_(6)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={
                nodes.collision_cylinder8_no_bottom014_No_Name_0.geometry
              }
              material={materials.No_Name}
              position={[0, 0.155, 0]}
              scale={[0.198, 0.492, 0.198]}
            />
          </group>
          <group position={[15.08, 5.43, 6.154]} scale={[1, 1, 0.549]}>
            <mesh
              geometry={nodes["FenceLongYellow_(5)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={nodes["collision_box011_Default-Material_0"].geometry}
              material={materials["Default-Material"]}
              position={[0, -0.102, -5.543]}
              scale={[0.13, 0.22, 5.724]}
            />
          </group>
          <group position={[15.08, 5.05, -0.049]}>
            <mesh
              geometry={nodes["FencePostYellow_(7)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={
                nodes.collision_cylinder8_no_bottom015_No_Name_0.geometry
              }
              material={materials.No_Name}
              position={[0, 0.155, 0]}
              scale={[0.198, 0.492, 0.198]}
            />
          </group>
          <group position={[15.08, 5.43, -0.206]} scale={[1, 1, 0.549]}>
            <mesh
              geometry={nodes["FenceLongYellow_(6)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={nodes["collision_box012_Default-Material_0"].geometry}
              material={materials["Default-Material"]}
              position={[0, -0.102, -5.543]}
              scale={[0.13, 0.22, 5.724]}
            />
          </group>
          <group position={[15.08, 5.05, -6.42]}>
            <mesh
              geometry={nodes["FencePostYellow_(8)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={
                nodes.collision_cylinder8_no_bottom016_No_Name_0.geometry
              }
              material={materials.No_Name}
              position={[0, 0.155, 0]}
              scale={[0.198, 0.492, 0.198]}
            />
          </group>
          <group position={[15.08, 5.43, -6.578]} scale={[1, 1, 0.549]}>
            <mesh
              geometry={nodes["FenceLongYellow_(7)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={nodes["collision_box013_Default-Material_0"].geometry}
              material={materials["Default-Material"]}
              position={[0, -0.102, -5.543]}
              scale={[0.13, 0.22, 5.724]}
            />
          </group>
          <group position={[15.08, 5.05, -12.769]}>
            <mesh
              geometry={nodes["FencePostYellow_(9)_Fence_0"].geometry}
              material={materials.Fence}
            />
            <mesh
              geometry={
                nodes.collision_cylinder8_no_bottom017_No_Name_0.geometry
              }
              material={materials.No_Name}
              position={[0, 0.155, 0]}
              scale={[0.198, 0.492, 0.198]}
            />
          </group>
        </group>

        {/* lights */}
        <mesh
          geometry={nodes.Level10VisualsExtra2_Level10VisualsExtra2_0.geometry}
          material={materials.Level10VisualsExtra2}
          position={[0, -4.79, 0]}
        />

        {/* pitch rail */}
        <mesh
          geometry={nodes.Level10VisualsExtra3_Fence_0.geometry}
          material={materials.Fence}
          position={[0, -4.79, 0]}
        />

        {/* net */}
        <mesh
          geometry={nodes.Level10VisualsNets_level10netting_0.geometry}
          material={materials.level10netting}
          position={[0, -4.79, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload("/stumble_guys_stumble_soccer.glb")
