/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Gazi Akviran (https://sketchfab.com/akviran)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/football-field-60331aee1f2e4c7fb545c464855bb378
Title: Football Field
*/

import { useGLTF } from "@react-three/drei"
import { RigidBody } from "@react-three/rapier"
import React, { useRef } from "react"

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF("./models/pitch-park.glb")

  return (
    <RigidBody type="fixed" colliders="trimesh">
      <group
        ref={group}
        {...props}
        dispose={null}
        scale={0.5}
        rotation-y={Math.PI}
        position-z={-30}
      >
        <group name="Sketchfab_Scene">
          <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
            <group name="root">
              <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                <group
                  name="Plane011_0"
                  position={[0.16, 0, 0]}
                  scale={[1.27, 1.19, 1.19]}
                />
                <group
                  name="Plane004_1"
                  position={[2.07, -3.06, -36.18]}
                  scale={[1.27, 1.19, 1.19]}
                >
                  {/* Park grass */}
                  <mesh
                    name="Object_5"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_5.geometry}
                    material={materials.dirt}
                  />

                  {/* Road Fence */}
                  <mesh
                    name="Object_6"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_6.geometry}
                    material={materials["Color.001"]}
                  />
                  <mesh
                    name="Object_7"
                    castShaddow
                    receiveShadow
                    geometry={nodes.Object_7.geometry}
                    material={materials.Fence2}
                  />

                  {/* Road */}
                  <mesh
                    name="Object_8"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_8.geometry}
                    material={materials.ModularRoads}
                  />

                  {/* Pitch frame */}
                  <mesh
                    name="Object_9"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_9.geometry}
                    material={materials.ColorPalette}
                  />
                  <mesh
                    name="Object_14"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_14.geometry}
                    material={materials.material}
                  />

                  {/* Pitch turf */}
                  <mesh
                    name="Object_15"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_15.geometry}
                    material={materials.zemin}
                  />

                  {/* Bus Stop */}
                  <mesh
                    name="Object_10"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_10.geometry}
                    material={materials.BusStop}
                  />
                  <mesh
                    name="Object_11"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_11.geometry}
                    material={materials.Glass}
                  />

                  {/* Trees */}
                  <mesh
                    name="Object_12"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_12.geometry}
                    material={materials["ColorPalette.001"]}
                  />

                  {/* Pavements */}
                  <mesh
                    name="Object_13"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_13.geometry}
                    material={materials["Color.003"]}
                  />

                  <mesh
                    name="Object_16"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_16.geometry}
                    material={materials.Saha}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </RigidBody>
  )
}

useGLTF.preload("/pitch-park.glb")
