/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei"
import { RigidBody } from "@react-three/rapier"
import React from "react"

export default function Stadium2(props) {
  const { nodes, materials } = useGLTF("/models/default.glb")
  return (
    <RigidBody type="fixed" colliders="trimesh" restitution={0.2} friction={1}>
      <group {...props} dispose={null}>
        <group scale={0.6}>
          <mesh
            receiveShadow
            geometry={nodes.Level10VisualsExtra_stands_wall_0001.geometry}
            material={materials["stands_wall.002"]}
          />
          <mesh
            receiveShadow
            geometry={nodes.Level10VisualsExtra_stands_wall_0001_1.geometry}
            material={materials["Mat001_Gun01.001"]}
          />
          <mesh
            receiveShadow
            geometry={nodes.Level10VisualsExtra_stands_wall_0001_2.geometry}
            material={materials["Mat001_Gun02.001"]}
          />
          <mesh
            receiveShadow
            geometry={nodes.Level10VisualsExtra_stands_wall_0001_3.geometry}
            material={materials["Mat001_Gun03.001"]}
          />
          <mesh
            receiveShadow
            geometry={nodes.Level10VisualsExtra_stands_wall_0001_4.geometry}
            material={materials["stands_seating3.002"]}
          />
          <mesh
            receiveShadow
            geometry={nodes.Level10VisualsExtra_stands_wall_0001_5.geometry}
            material={materials["Level10VisualsExtra2.002"]}
          />
          <mesh
            receiveShadow
            geometry={nodes.Level10VisualsExtra_stands_wall_0001_6.geometry}
            material={materials["Fence.002"]}
          />
          <mesh
            receiveShadow
            geometry={nodes.Level10VisualsExtra_stands_wall_0001_7.geometry}
            material={materials["soccerfield.002"]}
          />
          <mesh
            receiveShadow
            geometry={nodes.Level10VisualsExtra_stands_wall_0001_8.geometry}
            material={materials["lines.002"]}
          />
          <mesh
            receiveShadow
            geometry={nodes.Level10VisualsExtra_stands_wall_0001_9.geometry}
            material={materials["orange.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Level10VisualsExtra_stands_wall_0001_10.geometry}
            material={materials["goalpadding_orange.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Level10VisualsExtra_stands_wall_0001_11.geometry}
            material={materials["goal_orange.002"]}
          />
          <mesh
            receiveShadow
            geometry={nodes.Level10VisualsExtra_stands_wall_0001_12.geometry}
            material={materials["blue.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Level10VisualsExtra_stands_wall_0001_13.geometry}
            material={materials["goalpadding_blue.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Level10VisualsExtra_stands_wall_0001_14.geometry}
            material={materials["goal_blue.002"]}
          />
          <mesh
            receiveShadow
            geometry={nodes.Level10VisualsExtra_stands_wall_0001_15.geometry}
            material={materials["level10netting.002"]}
          />
          <mesh
            receiveShadow
            geometry={nodes.Level10VisualsExtra_stands_wall_0001_16.geometry}
            material={materials["No_Name.002"]}
          />
          <mesh
            receiveShadow
            geometry={nodes.Level10VisualsExtra_stands_wall_0001_17.geometry}
            material={materials["Default-Material.002"]}
          />
        </group>
      </group>
    </RigidBody>
  )
}

useGLTF.preload("/models/default.glb")
